# Generated by Django 5.2.16 on 2026-07-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('PERSON', 'Person'), ('ORG', 'Organization')], max_length=6)),
                ('color', models.CharField(default='slate', max_length=16)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['kind', 'name'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'name'), name='uniq_category_kind_name')],
            },
        ),
    ]
