# Generated by Django 5.2.16 on 2026-07-16 15:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
        ('insurance', '0004_vision_dental_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_year_start_month', models.PositiveSmallIntegerField(default=1)),
                ('plan_year_start_day', models.PositiveSmallIntegerField(default=1)),
                ('network', models.CharField(blank=True, max_length=80)),
                ('deductible_individual', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('deductible_family', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('oop_max_individual', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('oop_max_family', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('coinsurance_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('dental_annual_max', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('vision_allowance', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_plan', to='insurance.insurancepolicy')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CopayRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(max_length=80)),
                ('copay_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copay_rules', to='health.healthplan')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'service_type'), name='copayrule_unique')],
            },
        ),
    ]
