# Generated by Django 5.2.16 on 2026-07-16 16:33

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_banktransaction_banktxn_account_date_id'),
        ('cards', '0002_creditcardtransaction_cardtxn_card_date_id'),
        ('contacts', '0006_historicalperson_is_household_member_and_more'),
        ('finance', '0018_dental_vision_insurance_accounts'),
        ('health', '0002_healthplan_copayrule'),
        ('investments', '0016_investmenttransaction_invtxn_account_date_id_and_more'),
        ('organizations', '0002_branch_closed_day_branch_closed_month_and_more'),
        ('payables', '0008_payment_hsa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPrescription',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('drug_name', models.CharField(max_length=160)),
                ('dosage', models.CharField(blank=True, max_length=120)),
                ('date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('days_supply', models.PositiveIntegerField(blank=True, null=True)),
                ('refills_remaining', models.PositiveIntegerField(default=0)),
                ('next_refill_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_insurance', 'Pending insurance'), ('unpaid', 'Unpaid'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('disputed', 'Disputed'), ('written_off', 'Written off / adjusted'), ('overpaid', 'Overpaid (refund due)')], default='unpaid', max_length=18)),
                ('refund_expected', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('refunded', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('funding_source', models.CharField(blank=True, choices=[('bank', 'Bank account'), ('card', 'Credit card'), ('cash', 'Cash / other'), ('hsa', 'HSA')], max_length=8)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical prescription',
                'verbose_name_plural': 'historical prescriptions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('drug_name', models.CharField(max_length=160)),
                ('dosage', models.CharField(blank=True, max_length=120)),
                ('date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('days_supply', models.PositiveIntegerField(blank=True, null=True)),
                ('refills_remaining', models.PositiveIntegerField(default=0)),
                ('next_refill_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_insurance', 'Pending insurance'), ('unpaid', 'Unpaid'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('disputed', 'Disputed'), ('written_off', 'Written off / adjusted'), ('overpaid', 'Overpaid (refund due)')], default='unpaid', max_length=18)),
                ('refund_expected', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('refunded', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('funding_source', models.CharField(blank=True, choices=[('bank', 'Bank account'), ('card', 'Credit card'), ('cash', 'Cash / other'), ('hsa', 'HSA')], max_length=8)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('memo', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='healthdocument',
            name='healthdocument_one_owner',
        ),
        migrations.AddField(
            model_name='historicalprescription',
            name='bill',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payables.bill'),
        ),
        migrations.AddField(
            model_name='historicalprescription',
            name='cash_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.account'),
        ),
        migrations.AddField(
            model_name='historicalprescription',
            name='credit_card',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cards.creditcard'),
        ),
        migrations.AddField(
            model_name='historicalprescription',
            name='funding_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='banking.bankaccount'),
        ),
        migrations.AddField(
            model_name='historicalprescription',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprescription',
            name='hsa_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='investments.investmentaccount'),
        ),
        migrations.AddField(
            model_name='historicalprescription',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.person'),
        ),
        migrations.AddField(
            model_name='historicalprescription',
            name='pharmacy_organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='historicalprescription',
            name='prescriber_person',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.person'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='bill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_prescription', to='payables.bill'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.account'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cards.creditcard'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='funding_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='banking.bankaccount'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='hsa_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='investments.investmentaccount'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_prescriptions', to='contacts.person'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pharmacy_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_prescriptions', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescriber_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_prescriptions_written', to='contacts.person'),
        ),
        migrations.AddField(
            model_name='healthdocument',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='health.prescription'),
        ),
        migrations.AddConstraint(
            model_name='healthdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('encounter__isnull', False), ('invoice__isnull', True), ('person__isnull', True), ('prescription__isnull', True)), models.Q(('encounter__isnull', True), ('invoice__isnull', False), ('person__isnull', True), ('prescription__isnull', True)), models.Q(('encounter__isnull', True), ('invoice__isnull', True), ('person__isnull', True), ('prescription__isnull', False)), models.Q(('encounter__isnull', True), ('invoice__isnull', True), ('person__isnull', False), ('prescription__isnull', True)), _connector='OR'), name='healthdocument_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='prescription_cost_nonneg'),
        ),
    ]
