# Generated by Django 5.2.16 on 2026-07-16 18:49

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_historicalperson_is_household_member_and_more'),
        ('health', '0003_prescription'),
        ('insurance', '0004_vision_dental_types'),
        ('organizations', '0002_branch_closed_day_branch_closed_month_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('service_code', models.CharField(blank=True, max_length=40)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('place_of_service', models.CharField(blank=True, max_length=80)),
                ('billed', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('plan_discount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('allowed', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('plan_paid', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('deductible', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('copay', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('coinsurance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('not_covered', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('remark_codes', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClaimRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMedicalClaim',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('claim_number', models.CharField(blank=True, max_length=80)),
                ('member_id', models.CharField(blank=True, max_length=80)),
                ('group_number', models.CharField(blank=True, max_length=80)),
                ('service_date', models.DateField()),
                ('service_date_end', models.DateField(blank=True, null=True)),
                ('processed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_process', 'In process'), ('processed', 'Processed'), ('denied', 'Denied'), ('appealed', 'Appealed')], default='processed', max_length=12)),
                ('network', models.CharField(choices=[('in', 'In-network'), ('out', 'Out-of-network')], default='in', max_length=3)),
                ('total_billed', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_plan_discount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_allowed', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_plan_paid', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_deductible', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_copay', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_coinsurance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_not_covered', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_patient_responsibility', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical medical claim',
                'verbose_name_plural': 'historical medical claims',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MedicalClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('claim_number', models.CharField(blank=True, max_length=80)),
                ('member_id', models.CharField(blank=True, max_length=80)),
                ('group_number', models.CharField(blank=True, max_length=80)),
                ('service_date', models.DateField()),
                ('service_date_end', models.DateField(blank=True, null=True)),
                ('processed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_process', 'In process'), ('processed', 'Processed'), ('denied', 'Denied'), ('appealed', 'Appealed')], default='processed', max_length=12)),
                ('network', models.CharField(choices=[('in', 'In-network'), ('out', 'Out-of-network')], default='in', max_length=3)),
                ('total_billed', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_plan_discount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_allowed', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_plan_paid', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_deductible', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_copay', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_coinsurance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_not_covered', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('total_patient_responsibility', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-service_date', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='healthdocument',
            name='healthdocument_one_owner',
        ),
        migrations.AddField(
            model_name='historicalmedicalclaim',
            name='encounter',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='health.encounter'),
        ),
        migrations.AddField(
            model_name='historicalmedicalclaim',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmedicalclaim',
            name='invoice',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='health.providerinvoice'),
        ),
        migrations.AddField(
            model_name='historicalmedicalclaim',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.person'),
        ),
        migrations.AddField(
            model_name='historicalmedicalclaim',
            name='plan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='insurance.insurancepolicy'),
        ),
        migrations.AddField(
            model_name='historicalmedicalclaim',
            name='provider_organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='historicalmedicalclaim',
            name='provider_person',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.person'),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='health.encounter'),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim', to='health.providerinvoice'),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_claims', to='contacts.person'),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_claims', to='insurance.insurancepolicy'),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='provider_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_claims', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='medicalclaim',
            name='provider_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_claims_rendered', to='contacts.person'),
        ),
        migrations.AddField(
            model_name='claimremark',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='health.medicalclaim'),
        ),
        migrations.AddField(
            model_name='claimline',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='health.medicalclaim'),
        ),
        migrations.AddField(
            model_name='healthdocument',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='health.medicalclaim'),
        ),
        migrations.AddConstraint(
            model_name='healthdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('claim__isnull', True), ('encounter__isnull', False), ('invoice__isnull', True), ('person__isnull', True), ('prescription__isnull', True)), models.Q(('claim__isnull', True), ('encounter__isnull', True), ('invoice__isnull', False), ('person__isnull', True), ('prescription__isnull', True)), models.Q(('claim__isnull', True), ('encounter__isnull', True), ('invoice__isnull', True), ('person__isnull', True), ('prescription__isnull', False)), models.Q(('claim__isnull', False), ('encounter__isnull', True), ('invoice__isnull', True), ('person__isnull', True), ('prescription__isnull', True)), models.Q(('claim__isnull', True), ('encounter__isnull', True), ('invoice__isnull', True), ('person__isnull', False), ('prescription__isnull', True)), _connector='OR'), name='healthdocument_one_owner'),
        ),
    ]
