# Generated by Django 5.2.16 on 2026-07-10 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_banktransaction_card_historicalbanktransaction_card'),
        ('contacts', '0006_historicalperson_is_household_member_and_more'),
        ('finance', '0006_investment_accounts'),
        ('investments', '0001_initial'),
        ('organizations', '0002_branch_closed_day_branch_closed_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestmenttransaction',
            name='counter_investment_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='investments.investmentaccount'),
        ),
        migrations.AddField(
            model_name='historicalinvestmenttransaction',
            name='lot_carry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvestmenttransaction',
            name='paired_txn',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='investments.investmenttransaction'),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='counter_investment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='in_kind_transfers', to='investments.investmentaccount'),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='lot_carry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='paired_txn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='investments.investmenttransaction'),
        ),
        migrations.AlterField(
            model_name='historicalinvestmenttransaction',
            name='txn_type',
            field=models.CharField(choices=[('opening', 'Opening balance'), ('contribution', 'Contribution'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('dividend_reinvest', 'Dividend (reinvested)'), ('interest', 'Interest'), ('cap_gain_dist', 'Capital gains distribution'), ('return_of_capital', 'Return of capital'), ('fee', 'Fee'), ('split', 'Stock split'), ('in_kind_in', 'Securities transfer in (in-kind)'), ('in_kind_out', 'Securities transfer out (in-kind)'), ('worthless', 'Worthless write-off'), ('cash_merger', 'Cash buyout / merger')], max_length=20),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='txn_type',
            field=models.CharField(choices=[('opening', 'Opening balance'), ('contribution', 'Contribution'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('dividend_reinvest', 'Dividend (reinvested)'), ('interest', 'Interest'), ('cap_gain_dist', 'Capital gains distribution'), ('return_of_capital', 'Return of capital'), ('fee', 'Fee'), ('split', 'Stock split'), ('in_kind_in', 'Securities transfer in (in-kind)'), ('in_kind_out', 'Securities transfer out (in-kind)'), ('worthless', 'Worthless write-off'), ('cash_merger', 'Cash buyout / merger')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='investmenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('counter_investment_account', models.F('account')), _negated=True), name='investmenttransaction_no_self_inkind'),
        ),
    ]
