# Generated by Django 5.2.16 on 2026-07-11 00:41

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_in_kind_transfers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVestingGrant',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('kind', models.CharField(choices=[('dollar', 'Employer match ($)'), ('shares', 'Equity grant (shares)')], default='dollar', max_length=8)),
                ('label', models.CharField(max_length=120)),
                ('grant_date', models.DateField()),
                ('total', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('funded', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='investments.investmentaccount')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('security', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='investments.security')),
            ],
            options={
                'verbose_name': 'historical vesting grant',
                'verbose_name_plural': 'historical vesting grants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VestingGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('kind', models.CharField(choices=[('dollar', 'Employer match ($)'), ('shares', 'Equity grant (shares)')], default='dollar', max_length=8)),
                ('label', models.CharField(max_length=120)),
                ('grant_date', models.DateField()),
                ('total', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('funded', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vesting_grants', to='investments.investmentaccount')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vesting_grants', to='investments.security')),
            ],
            options={
                'ordering': ['grant_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VestingTranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vest_date', models.DateField()),
                ('cumulative_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='investments.vestinggrant')),
            ],
            options={
                'ordering': ['vest_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='vestinggrant',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='vestinggrant_total_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='vestingtranche',
            constraint=models.UniqueConstraint(fields=('grant', 'vest_date'), name='vestingtranche_unique_date'),
        ),
    ]
