# Generated by Django 5.2.16 on 2026-07-11 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_vesting'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestmenttransaction',
            name='basis_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvestmenttransaction',
            name='target_security',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='investments.security'),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='basis_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='target_security',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='investments.security'),
        ),
        migrations.AlterField(
            model_name='historicalinvestmenttransaction',
            name='txn_type',
            field=models.CharField(choices=[('opening', 'Opening balance'), ('contribution', 'Contribution'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('dividend_reinvest', 'Dividend (reinvested)'), ('interest', 'Interest'), ('cap_gain_dist', 'Capital gains distribution'), ('return_of_capital', 'Return of capital'), ('fee', 'Fee'), ('split', 'Stock split'), ('in_kind_in', 'Securities transfer in (in-kind)'), ('in_kind_out', 'Securities transfer out (in-kind)'), ('worthless', 'Worthless write-off'), ('cash_merger', 'Cash buyout / merger'), ('merger', 'Merger (stock-for-stock)'), ('spinoff', 'Spin-off')], max_length=20),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='txn_type',
            field=models.CharField(choices=[('opening', 'Opening balance'), ('contribution', 'Contribution'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('dividend_reinvest', 'Dividend (reinvested)'), ('interest', 'Interest'), ('cap_gain_dist', 'Capital gains distribution'), ('return_of_capital', 'Return of capital'), ('fee', 'Fee'), ('split', 'Stock split'), ('in_kind_in', 'Securities transfer in (in-kind)'), ('in_kind_out', 'Securities transfer out (in-kind)'), ('worthless', 'Worthless write-off'), ('cash_merger', 'Cash buyout / merger'), ('merger', 'Merger (stock-for-stock)'), ('spinoff', 'Spin-off')], max_length=20),
        ),
    ]
