# Generated by Django 5.2.16 on 2026-07-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_corporate_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvestmenttransaction',
            name='txn_type',
            field=models.CharField(choices=[('opening', 'Opening balance'), ('contribution', 'Contribution'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('dividend_reinvest', 'Dividend (reinvested)'), ('interest', 'Interest'), ('cap_gain_dist', 'Capital gains distribution'), ('return_of_capital', 'Return of capital'), ('fee', 'Fee'), ('split', 'Stock split'), ('in_kind_in', 'Securities transfer in (in-kind)'), ('in_kind_out', 'Securities transfer out (in-kind)'), ('worthless', 'Worthless write-off'), ('cash_merger', 'Cash buyout / merger'), ('merger', 'Merger (stock-for-stock)'), ('spinoff', 'Spin-off'), ('sell_short', 'Sell short'), ('buy_to_cover', 'Buy to cover'), ('margin_interest', 'Margin interest'), ('div_paid_short', 'Dividend paid (short)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='txn_type',
            field=models.CharField(choices=[('opening', 'Opening balance'), ('contribution', 'Contribution'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('dividend_reinvest', 'Dividend (reinvested)'), ('interest', 'Interest'), ('cap_gain_dist', 'Capital gains distribution'), ('return_of_capital', 'Return of capital'), ('fee', 'Fee'), ('split', 'Stock split'), ('in_kind_in', 'Securities transfer in (in-kind)'), ('in_kind_out', 'Securities transfer out (in-kind)'), ('worthless', 'Worthless write-off'), ('cash_merger', 'Cash buyout / merger'), ('merger', 'Merger (stock-for-stock)'), ('spinoff', 'Spin-off'), ('sell_short', 'Sell short'), ('buy_to_cover', 'Buy to cover'), ('margin_interest', 'Margin interest'), ('div_paid_short', 'Dividend paid (short)')], max_length=20),
        ),
    ]
