# Generated by Django 5.2.16 on 2026-07-11 22:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_leverage_txn_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsecurity',
            name='expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsecurity',
            name='multiplier',
            field=models.DecimalField(decimal_places=6, default=Decimal('100'), max_digits=20),
        ),
        migrations.AddField(
            model_name='historicalsecurity',
            name='option_right',
            field=models.CharField(blank=True, choices=[('call', 'Call'), ('put', 'Put')], max_length=4),
        ),
        migrations.AddField(
            model_name='historicalsecurity',
            name='strike',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalsecurity',
            name='underlying',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='investments.security'),
        ),
        migrations.AddField(
            model_name='security',
            name='expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='security',
            name='multiplier',
            field=models.DecimalField(decimal_places=6, default=Decimal('100'), max_digits=20),
        ),
        migrations.AddField(
            model_name='security',
            name='option_right',
            field=models.CharField(blank=True, choices=[('call', 'Call'), ('put', 'Put')], max_length=4),
        ),
        migrations.AddField(
            model_name='security',
            name='strike',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='security',
            name='underlying',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='option_contracts', to='investments.security'),
        ),
        migrations.AlterField(
            model_name='historicalinvestmenttransaction',
            name='txn_type',
            field=models.CharField(choices=[('opening', 'Opening balance'), ('contribution', 'Contribution'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('dividend_reinvest', 'Dividend (reinvested)'), ('interest', 'Interest'), ('cap_gain_dist', 'Capital gains distribution'), ('return_of_capital', 'Return of capital'), ('fee', 'Fee'), ('split', 'Stock split'), ('in_kind_in', 'Securities transfer in (in-kind)'), ('in_kind_out', 'Securities transfer out (in-kind)'), ('worthless', 'Worthless write-off'), ('cash_merger', 'Cash buyout / merger'), ('merger', 'Merger (stock-for-stock)'), ('spinoff', 'Spin-off'), ('sell_short', 'Sell short'), ('buy_to_cover', 'Buy to cover'), ('margin_interest', 'Margin interest'), ('div_paid_short', 'Dividend paid (short)'), ('opt_buy_open', 'Option — buy to open'), ('opt_sell_close', 'Option — sell to close'), ('opt_sell_open', 'Option — sell to open'), ('opt_buy_close', 'Option — buy to close'), ('opt_expire', 'Option — expire'), ('opt_exercise', 'Option — exercise'), ('opt_assign', 'Option — assignment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalsecurity',
            name='asset_class',
            field=models.CharField(choices=[('equity', 'Equity'), ('fixed_income', 'Fixed income'), ('cash', 'Cash & equivalents'), ('real_asset', 'Real assets'), ('derivative', 'Derivatives'), ('other', 'Other')], default='equity', max_length=14),
        ),
        migrations.AlterField(
            model_name='historicalsecurity',
            name='kind',
            field=models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('mutual_fund', 'Mutual fund'), ('bond', 'Bond'), ('cd', 'CD / Term deposit'), ('money_market', 'Money market'), ('option', 'Option'), ('other', 'Other')], default='stock', max_length=14),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='txn_type',
            field=models.CharField(choices=[('opening', 'Opening balance'), ('contribution', 'Contribution'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('dividend_reinvest', 'Dividend (reinvested)'), ('interest', 'Interest'), ('cap_gain_dist', 'Capital gains distribution'), ('return_of_capital', 'Return of capital'), ('fee', 'Fee'), ('split', 'Stock split'), ('in_kind_in', 'Securities transfer in (in-kind)'), ('in_kind_out', 'Securities transfer out (in-kind)'), ('worthless', 'Worthless write-off'), ('cash_merger', 'Cash buyout / merger'), ('merger', 'Merger (stock-for-stock)'), ('spinoff', 'Spin-off'), ('sell_short', 'Sell short'), ('buy_to_cover', 'Buy to cover'), ('margin_interest', 'Margin interest'), ('div_paid_short', 'Dividend paid (short)'), ('opt_buy_open', 'Option — buy to open'), ('opt_sell_close', 'Option — sell to close'), ('opt_sell_open', 'Option — sell to open'), ('opt_buy_close', 'Option — buy to close'), ('opt_expire', 'Option — expire'), ('opt_exercise', 'Option — exercise'), ('opt_assign', 'Option — assignment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='security',
            name='asset_class',
            field=models.CharField(choices=[('equity', 'Equity'), ('fixed_income', 'Fixed income'), ('cash', 'Cash & equivalents'), ('real_asset', 'Real assets'), ('derivative', 'Derivatives'), ('other', 'Other')], default='equity', max_length=14),
        ),
        migrations.AlterField(
            model_name='security',
            name='kind',
            field=models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('mutual_fund', 'Mutual fund'), ('bond', 'Bond'), ('cd', 'CD / Term deposit'), ('money_market', 'Money market'), ('option', 'Option'), ('other', 'Other')], default='stock', max_length=14),
        ),
    ]
