# Generated by Django 5.2.16 on 2026-07-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestmenttransaction',
            name='tax_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='tax_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
