# Generated by Django 5.2.16 on 2026-07-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_contribution_tax_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestmentaccount',
            name='hsa_coverage',
            field=models.CharField(blank=True, choices=[('self_only', 'Self-only'), ('family', 'Family')], default='self_only', max_length=10),
        ),
        migrations.AddField(
            model_name='investmentaccount',
            name='hsa_coverage',
            field=models.CharField(blank=True, choices=[('self_only', 'Self-only'), ('family', 'Family')], default='self_only', max_length=10),
        ),
    ]
