# Generated by Django 5.2.16 on 2026-07-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_hsa_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsecurity',
            name='track_lots',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='security',
            name='track_lots',
            field=models.BooleanField(default=True),
        ),
    ]
