# Generated by Django 5.2.16 on 2026-07-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0009_security_track_lots'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsecurity',
            name='track_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='security',
            name='track_price',
            field=models.BooleanField(default=True),
        ),
    ]
