# Generated by Django 5.2.16 on 2026-07-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0010_security_track_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestmenttransaction',
            name='settlement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='settlement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
