# Generated by Django 5.2.16 on 2026-07-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0011_historicalinvestmenttransaction_settlement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestmenttransaction',
            name='declaration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvestmenttransaction',
            name='ex_dividend_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvestmenttransaction',
            name='record_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='declaration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='ex_dividend_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='record_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
