# Generated by Django 5.2.16 on 2026-07-14 16:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0013_alter_historicalinvestmenttransaction_txn_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_year', models.PositiveIntegerField(unique=True)),
                ('ira', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('ira_catchup', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('hsa_self', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('hsa_family', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('hsa_catchup', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
            ],
            options={
                'ordering': ['-tax_year'],
            },
        ),
    ]
