# Generated by Django 5.2.16 on 2026-07-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_banktransaction_banktxn_account_date_id'),
        ('contacts', '0006_historicalperson_is_household_member_and_more'),
        ('finance', '0012_journalline_jline_account_entry'),
        ('investments', '0015_seed_contribution_limits'),
        ('organizations', '0002_branch_closed_day_branch_closed_month_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='investmenttransaction',
            index=models.Index(fields=['account', 'date', 'id'], name='invtxn_account_date_id'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(condition=models.Q(('open', True)), fields=['account', 'security'], name='lot_open_acct_security'),
        ),
    ]
