# Generated by Django 5.2.16 on 2026-07-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0016_investmenttransaction_invtxn_account_date_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestmenttransaction',
            name='stock_fmv',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='stock_fmv',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinvestmenttransaction',
            name='txn_type',
            field=models.CharField(choices=[('opening', 'Opening balance'), ('contribution', 'Contribution'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('buy', 'Buy'), ('sell', 'Sell'), ('cash_in_lieu', 'Cash in lieu'), ('dividend', 'Dividend'), ('dividend_reinvest', 'Dividend (reinvested)'), ('interest', 'Interest'), ('cap_gain_dist', 'Capital gains distribution'), ('return_of_capital', 'Return of capital'), ('fee', 'Fee'), ('split', 'Stock split'), ('in_kind_in', 'Securities transfer in (in-kind)'), ('in_kind_out', 'Securities transfer out (in-kind)'), ('worthless', 'Worthless write-off'), ('cash_merger', 'Cash buyout / merger'), ('merger', 'Merger (stock / cash & stock)'), ('spinoff', 'Spin-off'), ('sell_short', 'Sell short'), ('buy_to_cover', 'Buy to cover'), ('margin_interest', 'Margin interest'), ('div_paid_short', 'Dividend paid (short)'), ('opt_buy_open', 'Option — buy to open'), ('opt_sell_close', 'Option — sell to close'), ('opt_sell_open', 'Option — sell to open'), ('opt_buy_close', 'Option — buy to close'), ('opt_expire', 'Option — expire'), ('opt_exercise', 'Option — exercise'), ('opt_assign', 'Option — assignment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='txn_type',
            field=models.CharField(choices=[('opening', 'Opening balance'), ('contribution', 'Contribution'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('buy', 'Buy'), ('sell', 'Sell'), ('cash_in_lieu', 'Cash in lieu'), ('dividend', 'Dividend'), ('dividend_reinvest', 'Dividend (reinvested)'), ('interest', 'Interest'), ('cap_gain_dist', 'Capital gains distribution'), ('return_of_capital', 'Return of capital'), ('fee', 'Fee'), ('split', 'Stock split'), ('in_kind_in', 'Securities transfer in (in-kind)'), ('in_kind_out', 'Securities transfer out (in-kind)'), ('worthless', 'Worthless write-off'), ('cash_merger', 'Cash buyout / merger'), ('merger', 'Merger (stock / cash & stock)'), ('spinoff', 'Spin-off'), ('sell_short', 'Sell short'), ('buy_to_cover', 'Buy to cover'), ('margin_interest', 'Margin interest'), ('div_paid_short', 'Dividend paid (short)'), ('opt_buy_open', 'Option — buy to open'), ('opt_sell_close', 'Option — sell to close'), ('opt_sell_open', 'Option — sell to open'), ('opt_buy_close', 'Option — buy to close'), ('opt_expire', 'Option — expire'), ('opt_exercise', 'Option — exercise'), ('opt_assign', 'Option — assignment')], max_length=20),
        ),
    ]
