# Generated by Django 5.2.16 on 2026-07-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0003_backfill_compliance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvehicle',
            name='insurance_carrier',
        ),
        migrations.RemoveField(
            model_name='historicalvehicle',
            name='insurance_expiry',
        ),
        migrations.RemoveField(
            model_name='historicalvehicle',
            name='insurance_policy_number',
        ),
        migrations.RemoveField(
            model_name='historicalvehicle',
            name='insurer_organization',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance_carrier',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance_expiry',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance_policy_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurer_organization',
        ),
        migrations.AlterField(
            model_name='historicalvehiclecostevent',
            name='kind',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('improvement', 'Improvement / upgrade'), ('fuel', 'Fuel / charging'), ('service', 'Service'), ('repair', 'Repair'), ('registration', 'Registration / road tax'), ('inspection', 'Inspection'), ('emissions', 'Emissions / smog'), ('lease_payment', 'Lease payment'), ('lease_deposit', 'Lease deposit'), ('tax_fee', 'Tax / fee'), ('property_tax', 'Personal property tax'), ('other', 'Other')], default='fuel', max_length=16),
        ),
        migrations.AlterField(
            model_name='vehiclecostevent',
            name='kind',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('improvement', 'Improvement / upgrade'), ('fuel', 'Fuel / charging'), ('service', 'Service'), ('repair', 'Repair'), ('registration', 'Registration / road tax'), ('inspection', 'Inspection'), ('emissions', 'Emissions / smog'), ('lease_payment', 'Lease payment'), ('lease_deposit', 'Lease deposit'), ('tax_fee', 'Tax / fee'), ('property_tax', 'Personal property tax'), ('other', 'Other')], default='fuel', max_length=16),
        ),
    ]
