# Generated by Django 5.2.16 on 2026-07-08 18:12

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('first_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('preferred_name', models.CharField(blank=True, max_length=80)),
                ('pronouns', models.CharField(blank=True, max_length=40)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Prefer not to say')], default='U', max_length=1)),
                ('dob_year', models.SmallIntegerField(blank=True, null=True)),
                ('dob_month', models.SmallIntegerField(blank=True, null=True)),
                ('dob_day', models.SmallIntegerField(blank=True, null=True)),
                ('is_deceased', models.BooleanField(default=False)),
                ('dod_year', models.SmallIntegerField(blank=True, null=True)),
                ('dod_month', models.SmallIntegerField(blank=True, null=True)),
                ('dod_day', models.SmallIntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced'), ('separated', 'Separated'), ('partnered', 'Partnered')], max_length=16)),
                ('anniversary_year', models.SmallIntegerField(blank=True, null=True)),
                ('anniversary_month', models.SmallIntegerField(blank=True, null=True)),
                ('anniversary_day', models.SmallIntegerField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('education', models.CharField(blank=True, max_length=120)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], max_length=8)),
                ('dietary', models.CharField(blank=True, max_length=120)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='person_photos/')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPerson',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('first_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('preferred_name', models.CharField(blank=True, max_length=80)),
                ('pronouns', models.CharField(blank=True, max_length=40)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Prefer not to say')], default='U', max_length=1)),
                ('dob_year', models.SmallIntegerField(blank=True, null=True)),
                ('dob_month', models.SmallIntegerField(blank=True, null=True)),
                ('dob_day', models.SmallIntegerField(blank=True, null=True)),
                ('is_deceased', models.BooleanField(default=False)),
                ('dod_year', models.SmallIntegerField(blank=True, null=True)),
                ('dod_month', models.SmallIntegerField(blank=True, null=True)),
                ('dod_day', models.SmallIntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced'), ('separated', 'Separated'), ('partnered', 'Partnered')], max_length=16)),
                ('anniversary_year', models.SmallIntegerField(blank=True, null=True)),
                ('anniversary_month', models.SmallIntegerField(blank=True, null=True)),
                ('anniversary_day', models.SmallIntegerField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('education', models.CharField(blank=True, max_length=120)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], max_length=8)),
                ('dietary', models.CharField(blank=True, max_length=120)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('photo', models.TextField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical person',
                'verbose_name_plural': 'historical people',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
