# Generated by Django 5.2.16 on 2026-07-09 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_person_categories_historicalimportantdate_and_more'),
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='address_one_owner',
        ),
        migrations.RemoveConstraint(
            model_name='contactchannel',
            name='contactchannel_one_owner',
        ),
        migrations.AddField(
            model_name='address',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='families.family'),
        ),
        migrations.AddField(
            model_name='contactchannel',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='families.family'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='family',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='families.family'),
        ),
        migrations.AddField(
            model_name='historicalcontactchannel',
            name='family',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='families.family'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('family__isnull', True), ('person__isnull', False)), models.Q(('family__isnull', False), ('person__isnull', True)), _connector='OR'), name='address_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='contactchannel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('family__isnull', True), ('person__isnull', False)), models.Q(('family__isnull', False), ('person__isnull', True)), _connector='OR'), name='contactchannel_one_owner'),
        ),
    ]
