# Generated by Django 5.2.16 on 2026-07-09 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_address_address_one_owner_and_more'),
        ('families', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='address_one_owner',
        ),
        migrations.RemoveConstraint(
            model_name='contactchannel',
            name='contactchannel_one_owner',
        ),
        migrations.AddField(
            model_name='address',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='address',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='contactchannel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='contactchannel',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='historicalcontactchannel',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='historicalcontactchannel',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('branch__isnull', True), ('family__isnull', True), ('organization__isnull', True), ('person__isnull', False)), models.Q(('branch__isnull', True), ('family__isnull', False), ('organization__isnull', True), ('person__isnull', True)), models.Q(('branch__isnull', True), ('family__isnull', True), ('organization__isnull', False), ('person__isnull', True)), models.Q(('branch__isnull', False), ('family__isnull', True), ('organization__isnull', True), ('person__isnull', True)), _connector='OR'), name='address_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='contactchannel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('branch__isnull', True), ('family__isnull', True), ('organization__isnull', True), ('person__isnull', False)), models.Q(('branch__isnull', True), ('family__isnull', False), ('organization__isnull', True), ('person__isnull', True)), models.Q(('branch__isnull', True), ('family__isnull', True), ('organization__isnull', False), ('person__isnull', True)), models.Q(('branch__isnull', False), ('family__isnull', True), ('organization__isnull', True), ('person__isnull', True)), _connector='OR'), name='contactchannel_one_owner'),
        ),
    ]
