# Generated by Django 5.2.16 on 2026-07-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_address_address_one_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='is_household_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_household_member',
            field=models.BooleanField(default=False),
        ),
    ]
