# Generated by Django 5.2.16 on 2026-07-15 21:38

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0004_banktransaction_banktxn_account_date_id'),
        ('cards', '0002_creditcardtransaction_cardtxn_card_date_id'),
        ('contacts', '0006_historicalperson_is_household_member_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0015_insurance_accounts'),
        ('organizations', '0002_branch_closed_day_branch_closed_month_and_more'),
        ('payables', '0007_historicalpayment_is_locked_historicalpayment_loan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInsurancePolicy',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('policy_type', models.CharField(choices=[('auto', 'Auto'), ('home', 'Homeowners'), ('renters', 'Renters'), ('health', 'Health'), ('life', 'Life'), ('umbrella', 'Umbrella / liability'), ('disability', 'Disability'), ('pet', 'Pet'), ('other', 'Other')], default='auto', max_length=12)),
                ('nickname', models.CharField(blank=True, max_length=120)),
                ('plan_name', models.CharField(blank=True, max_length=120)),
                ('policy_number', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('lapsed', 'Lapsed'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('premium_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('premium_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semi-annual'), ('annual', 'Annual'), ('one_time', 'One-time')], default='annual', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('currency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.currency')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('insurer_organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
                ('insurer_person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.person')),
            ],
            options={
                'verbose_name': 'historical insurance policy',
                'verbose_name_plural': 'historical insurance policys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('policy_type', models.CharField(choices=[('auto', 'Auto'), ('home', 'Homeowners'), ('renters', 'Renters'), ('health', 'Health'), ('life', 'Life'), ('umbrella', 'Umbrella / liability'), ('disability', 'Disability'), ('pet', 'Pet'), ('other', 'Other')], default='auto', max_length=12)),
                ('nickname', models.CharField(blank=True, max_length=120)),
                ('plan_name', models.CharField(blank=True, max_length=120)),
                ('policy_number', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('lapsed', 'Lapsed'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('premium_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('premium_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semi-annual'), ('annual', 'Annual'), ('one_time', 'One-time')], default='annual', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.currency')),
                ('insurer_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_policies', to='organizations.organization')),
                ('insurer_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_policies', to='contacts.person')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalInsurancePremium',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('covers_from', models.DateField(blank=True, null=True)),
                ('covers_through', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('funding_source', models.CharField(choices=[('bank', 'Bank account'), ('card', 'Credit card'), ('cash', 'Cash / other'), ('none', 'Unpaid (record bill only)')], default='none', max_length=8)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bill', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payables.bill')),
                ('cash_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.account')),
                ('credit_card', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cards.creditcard')),
                ('funding_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='banking.bankaccount')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payables.payment')),
                ('policy', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='insurance.insurancepolicy')),
            ],
            options={
                'verbose_name': 'historical insurance premium',
                'verbose_name_plural': 'historical insurance premiums',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InsurancePremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('covers_from', models.DateField(blank=True, null=True)),
                ('covers_through', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('funding_source', models.CharField(choices=[('bank', 'Bank account'), ('card', 'Credit card'), ('cash', 'Cash / other'), ('none', 'Unpaid (record bill only)')], default='none', max_length=8)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('bill', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_premium', to='payables.bill')),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.account')),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cards.creditcard')),
                ('funding_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='banking.bankaccount')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payables.payment')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiums', to='insurance.insurancepolicy')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='insurance.insurancepolicy')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PolicyCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coverage_type', models.CharField(max_length=80)),
                ('limit_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('deductible_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('premium_portion', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='insurance.insurancepolicy')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PolicyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('policyholder', 'Policyholder'), ('insured', 'Insured'), ('dependent', 'Dependent'), ('driver', 'Driver'), ('beneficiary', 'Beneficiary')], default='insured', max_length=12)),
                ('beneficiary_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('relationship_note', models.CharField(blank=True, max_length=120)),
                ('covered_from', models.DateField(blank=True, null=True)),
                ('covered_to', models.DateField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_memberships', to='contacts.person')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='insurance.insurancepolicy')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='insurancepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('insurer_organization__isnull', False), ('insurer_person__isnull', False), _negated=True), name='insurancepolicy_one_insurer'),
        ),
        migrations.AddConstraint(
            model_name='insurancepremium',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='insurancepremium_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='policyasset',
            constraint=models.UniqueConstraint(fields=('policy', 'content_type', 'object_id'), name='policyasset_unique'),
        ),
        migrations.AddConstraint(
            model_name='policymember',
            constraint=models.UniqueConstraint(fields=('policy', 'person', 'role'), name='policymember_unique'),
        ),
    ]
