# Generated by Django 5.2.16 on 2026-07-15 23:28

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0004_drop_insurance_fields'),
        ('banking', '0004_banktransaction_banktxn_account_date_id'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0015_insurance_accounts'),
        ('insurance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalClaim',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('claim_number', models.CharField(blank=True, max_length=80)),
                ('loss_date', models.DateField()),
                ('reported_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('paid', 'Paid'), ('denied', 'Denied'), ('closed', 'Closed')], default='open', max_length=10)),
                ('settlement_kind', models.CharField(choices=[('reimbursement', 'Reimbursement'), ('total_loss', 'Total loss (auto write-off)')], default='reimbursement', max_length=14)),
                ('deductible_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('payout_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('payout_destination', models.CharField(choices=[('bank', 'Bank account'), ('cash', 'Cash / other'), ('none', 'No payout yet')], default='none', max_length=6)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('posting_version', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='banking.bankaccount')),
                ('bank_txn', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='banking.banktransaction')),
                ('cash_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.account')),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
                ('disposal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='automobile.vehicledisposal')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.journalentry')),
                ('loss_expense_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.account')),
                ('policy', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='insurance.insurancepolicy')),
            ],
            options={
                'verbose_name': 'historical claim',
                'verbose_name_plural': 'historical claims',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('claim_number', models.CharField(blank=True, max_length=80)),
                ('loss_date', models.DateField()),
                ('reported_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('paid', 'Paid'), ('denied', 'Denied'), ('closed', 'Closed')], default='open', max_length=10)),
                ('settlement_kind', models.CharField(choices=[('reimbursement', 'Reimbursement'), ('total_loss', 'Total loss (auto write-off)')], default='reimbursement', max_length=14)),
                ('deductible_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('payout_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('payout_destination', models.CharField(choices=[('bank', 'Bank account'), ('cash', 'Cash / other'), ('none', 'No payout yet')], default='none', max_length=6)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('posting_version', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='banking.bankaccount')),
                ('bank_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='banking.banktransaction')),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.account')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('disposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='automobile.vehicledisposal')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.journalentry')),
                ('loss_expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.insurancepolicy')),
            ],
            options={
                'ordering': ['-loss_date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('payout_amount__gte', 0)), name='claim_payout_nonnegative'), models.CheckConstraint(condition=models.Q(('bank_account__isnull', False), ('cash_account__isnull', False), _negated=True), name='claim_one_destination_account')],
            },
        ),
    ]
