# Generated by Django 5.2.16 on 2026-07-16 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_historicalclaim_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('doc_type', models.CharField(choices=[('policy_contract', 'Policy contract'), ('declaration_page', 'Declaration page'), ('id_card', 'ID card'), ('receipt', 'Receipt'), ('correspondence', 'Correspondence'), ('claim', 'Claim document'), ('other', 'Other')], default='other', max_length=16)),
                ('file', models.FileField(upload_to='insurance_docs/')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='insurance.claim')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='insurance.insurancepolicy')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
