# Generated by Django 5.2.16 on 2026-07-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_policydocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinsurancepolicy',
            name='policy_type',
            field=models.CharField(choices=[('auto', 'Auto'), ('home', 'Homeowners'), ('renters', 'Renters'), ('health', 'Health'), ('dental', 'Dental'), ('vision', 'Vision'), ('life', 'Life'), ('umbrella', 'Umbrella / liability'), ('disability', 'Disability'), ('pet', 'Pet'), ('other', 'Other')], default='auto', max_length=12),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='policy_type',
            field=models.CharField(choices=[('auto', 'Auto'), ('home', 'Homeowners'), ('renters', 'Renters'), ('health', 'Health'), ('dental', 'Dental'), ('vision', 'Vision'), ('life', 'Life'), ('umbrella', 'Umbrella / liability'), ('disability', 'Disability'), ('pet', 'Pet'), ('other', 'Other')], default='auto', max_length=12),
        ),
    ]
