# Generated by Django 5.2.16 on 2026-07-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0003_bank_charges_and_headers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('activity', models.CharField(max_length=40)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='postingmap_owner_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'activity'), name='uniq_postingmap_owner_activity')],
            },
        ),
    ]
