# Generated by Django 5.2.16 on 2026-07-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_historicalperson_is_household_member_and_more'),
        ('finance', '0011_loans_accounts'),
        ('organizations', '0002_branch_closed_day_branch_closed_month_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', 'entry'], name='jline_account_entry'),
        ),
    ]
