# Generated by Django 5.2.16 on 2026-07-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_logo_tenant_palette_invitation_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='tenant',
            name='date_format',
            field=models.CharField(choices=[('iso', '2026-07-09'), ('dmy', '09-07-2026'), ('mdy', '07/09/2026'), ('long', '09 Jul 2026')], default='iso', max_length=8),
        ),
        migrations.AddField(
            model_name='tenant',
            name='number_format',
            field=models.CharField(choices=[('plain', '1234.56'), ('thousands', '1,234.56'), ('indian', '1,23,456.78')], default='thousands', max_length=12),
        ),
        migrations.AddField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
