# Generated by Django 5.2.16 on 2026-07-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_currency_tenant_date_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='accounting_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='accounting_mode',
            field=models.CharField(choices=[('standard', 'Standard'), ('expert', 'Expert')], default='standard', max_length=8),
        ),
    ]
