# Generated by Django 5.2.16 on 2026-07-09 13:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_address_address_one_owner_and_more'),
        ('organizations', '0001_initial'),
        ('relationships', '0002_historicalpersonrelationship_personrelationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPersonOrgRelationship',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('role_note', models.CharField(blank=True, max_length=200)),
                ('from_year', models.SmallIntegerField(blank=True, null=True)),
                ('from_month', models.SmallIntegerField(blank=True, null=True)),
                ('from_day', models.SmallIntegerField(blank=True, null=True)),
                ('to_year', models.SmallIntegerField(blank=True, null=True)),
                ('to_month', models.SmallIntegerField(blank=True, null=True)),
                ('to_day', models.SmallIntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
                ('person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.person')),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='relationships.personorgrelationshiptype')),
            ],
            options={
                'verbose_name': 'historical person org relationship',
                'verbose_name_plural': 'historical person org relationships',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PersonOrgRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('role_note', models.CharField(blank=True, max_length=200)),
                ('from_year', models.SmallIntegerField(blank=True, null=True)),
                ('from_month', models.SmallIntegerField(blank=True, null=True)),
                ('from_day', models.SmallIntegerField(blank=True, null=True)),
                ('to_year', models.SmallIntegerField(blank=True, null=True)),
                ('to_month', models.SmallIntegerField(blank=True, null=True)),
                ('to_day', models.SmallIntegerField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_links', to='organizations.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_links', to='contacts.person')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edges', to='relationships.personorgrelationshiptype')),
            ],
            options={
                'ordering': ['organization__name', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('person', 'organization', 'type'), name='personorgrelationship_unique')],
            },
        ),
    ]
