# Generated by Django 5.2.16 on 2026-07-12 22:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('kind', models.CharField(choices=[('due_on_receipt', 'Due on receipt'), ('net_days', 'Net N days'), ('day_of_month', 'Day of month'), ('specific_date', 'Specific date')], default='net_days', max_length=16)),
                ('net_days', models.PositiveSmallIntegerField(default=0)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('discount_days', models.PositiveSmallIntegerField(default=0)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='uniq_payment_term_name')],
            },
        ),
    ]
