# Generated by Django 5.2.16 on 2026-07-13 00:33

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_payables_accounts'),
        ('organizations', '0002_branch_closed_day_branch_closed_month_and_more'),
        ('payables', '0002_seed_payment_terms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('upc', models.CharField(blank=True, max_length=40)),
                ('kind', models.CharField(choices=[('good', 'Good'), ('service', 'Service')], default='good', max_length=8)),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('capitalize_default', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('asset_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.account')),
                ('default_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.account')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical item',
                'verbose_name_plural': 'historical items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('upc', models.CharField(blank=True, max_length=40)),
                ('kind', models.CharField(choices=[('good', 'Good'), ('service', 'Service')], default='good', max_length=8)),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('capitalize_default', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asset_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account')),
                ('default_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(blank=True, max_length=120)),
                ('sku', models.CharField(max_length=60)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='payables.item')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ['store_name', 'sku'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['upc'], name='payables_item_upc_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemsku',
            constraint=models.UniqueConstraint(fields=('item', 'store', 'sku'), name='uniq_itemsku_item_store_sku'),
        ),
    ]
