# Generated by Django 5.2.16 on 2026-07-15 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('loans', '0002_alter_historicalloantransaction_funding_source_and_more'),
        ('payables', '0006_historicalpayment_payment_paymentallocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='loan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='loan_txn',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.loantransaction'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='source_content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='source_object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='loan_txn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='loans.loantransaction'),
        ),
        migrations.AddField(
            model_name='payment',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='source_object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='funding_kind',
            field=models.CharField(choices=[('bank', 'Bank account'), ('card', 'Credit card'), ('cash', 'Cash / other'), ('loan', 'Loan proceeds')], default='cash', max_length=8),
        ),
        migrations.AlterField(
            model_name='payment',
            name='funding_kind',
            field=models.CharField(choices=[('bank', 'Bank account'), ('card', 'Credit card'), ('cash', 'Cash / other'), ('loan', 'Loan proceeds')], default='cash', max_length=8),
        ),
    ]
