# Generated by Django 5.2.16 on 2026-07-16 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0016_investmenttransaction_invtxn_account_date_id_and_more'),
        ('payables', '0007_historicalpayment_is_locked_historicalpayment_loan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='hsa_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='investments.investmentaccount'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='hsa_txn',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='investments.investmenttransaction'),
        ),
        migrations.AddField(
            model_name='payment',
            name='hsa_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='investments.investmentaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='hsa_txn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='investments.investmenttransaction'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='funding_kind',
            field=models.CharField(choices=[('bank', 'Bank account'), ('card', 'Credit card'), ('cash', 'Cash / other'), ('loan', 'Loan proceeds'), ('hsa', 'HSA')], default='cash', max_length=8),
        ),
        migrations.AlterField(
            model_name='payment',
            name='funding_kind',
            field=models.CharField(choices=[('bank', 'Bank account'), ('card', 'Credit card'), ('cash', 'Cash / other'), ('loan', 'Loan proceeds'), ('hsa', 'HSA')], default='cash', max_length=8),
        ),
    ]
