# Generated by Django 5.2.16 on 2026-07-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalloantransaction',
            name='funding_source',
            field=models.CharField(choices=[('bank', 'Bank account'), ('cash', 'Cash on hand'), ('external', 'External / another party'), ('payable', 'Payable (dealer bill)')], default='external', max_length=10),
        ),
        migrations.AlterField(
            model_name='loantransaction',
            name='funding_source',
            field=models.CharField(choices=[('bank', 'Bank account'), ('cash', 'Cash on hand'), ('external', 'External / another party'), ('payable', 'Payable (dealer bill)')], default='external', max_length=10),
        ),
    ]
