# Generated by Django 5.2.16 on 2026-07-16 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('doc_type', models.CharField(choices=[('deed', 'Deed / title'), ('purchase_agreement', 'Purchase agreement'), ('closing_disclosure', 'Closing disclosure'), ('tax_bill', 'Property tax bill'), ('insurance', 'Insurance'), ('appraisal', 'Appraisal / inspection'), ('receipt', 'Receipt'), ('correspondence', 'Correspondence'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='realestate_docs/')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='realestate.property')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
