# Generated by Django 5.2.16 on 2026-07-10 00:05

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0005_remove_address_address_one_owner_and_more'),
        ('finance', '0003_bank_charges_and_headers'),
        ('organizations', '0002_branch_closed_day_branch_closed_month_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings')], default='checking', max_length=10)),
                ('nickname', models.CharField(max_length=120)),
                ('number', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('opened_year', models.SmallIntegerField(blank=True, null=True)),
                ('opened_month', models.SmallIntegerField(blank=True, null=True)),
                ('opened_day', models.SmallIntegerField(blank=True, null=True)),
                ('closed_year', models.SmallIntegerField(blank=True, null=True)),
                ('closed_month', models.SmallIntegerField(blank=True, null=True)),
                ('closed_day', models.SmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='organizations.organization')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='organizations.branch')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.currency')),
                ('gl_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to='finance.account')),
            ],
            options={
                'ordering': ['nickname'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBankAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings')], default='checking', max_length=10)),
                ('nickname', models.CharField(max_length=120)),
                ('number', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('opened_year', models.SmallIntegerField(blank=True, null=True)),
                ('opened_month', models.SmallIntegerField(blank=True, null=True)),
                ('opened_day', models.SmallIntegerField(blank=True, null=True)),
                ('closed_year', models.SmallIntegerField(blank=True, null=True)),
                ('closed_month', models.SmallIntegerField(blank=True, null=True)),
                ('closed_day', models.SmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch')),
                ('currency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.currency')),
                ('gl_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.account')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bank account',
                'verbose_name_plural': 'historical bank accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBankTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('txn_type', models.CharField(choices=[('opening', 'Opening balance'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('interest', 'Interest'), ('fee', 'Fee'), ('charge', 'Charge'), ('transfer_out', 'Transfer out'), ('transfer_in', 'Transfer in')], max_length=12)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('counter_external', models.CharField(blank=True, max_length=160)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('cleared', models.BooleanField(default=False)),
                ('posting_version', models.PositiveIntegerField(default=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='banking.bankaccount')),
                ('category_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.account')),
                ('counter_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='banking.bankaccount')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.journalentry')),
                ('payee_organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
                ('payee_person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.person')),
            ],
            options={
                'verbose_name': 'historical bank transaction',
                'verbose_name_plural': 'historical bank transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BankAccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='banking.bankaccount')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_holdings', to='contacts.person')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
                'constraints': [models.UniqueConstraint(fields=('account', 'person'), name='bankaccountholder_unique')],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('txn_type', models.CharField(choices=[('opening', 'Opening balance'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('interest', 'Interest'), ('fee', 'Fee'), ('charge', 'Charge'), ('transfer_out', 'Transfer out'), ('transfer_in', 'Transfer in')], max_length=12)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('counter_external', models.CharField(blank=True, max_length=160)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('cleared', models.BooleanField(default=False)),
                ('posting_version', models.PositiveIntegerField(default=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount')),
                ('category_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account')),
                ('counter_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counter_transactions', to='banking.bankaccount')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.journalentry')),
                ('payee_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_txns', to='organizations.organization')),
                ('payee_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_txns', to='contacts.person')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('payee_organization__isnull', False), ('payee_person__isnull', False), _negated=True), name='banktransaction_one_payee'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='banktransaction_amount_positive')],
            },
        ),
    ]
