# Generated by Django 5.2.16 on 2026-07-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_banktransaction_card_historicalbanktransaction_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='apr',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='term_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbankaccount',
            name='apr',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='historicalbankaccount',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbankaccount',
            name='term_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('cd', 'Certificate of Deposit')], default='checking', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalbankaccount',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('cd', 'Certificate of Deposit')], default='checking', max_length=10),
        ),
    ]
